# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Algorithm-Evolutionary
version:      0.54
version_from: Evolutionary.pm
installdirs:  site
requires:
    Algorithm::Permute:            0.01
    B::Deparse:                    0.56
    Math::Random:                  0.63
    Test::Simple:                  0.44
    Tree::DAG_Node:                1.04
    XML::LibXML:                   1.5
    XML::Parser::EasyTree:         0.01

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
