# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Algorithm-Evolutionary
version:      0.55
version_from: lib/Algorithm/Evolutionary.pm
installdirs:  site
requires:
    Algorithm::Permute:            0.01
    B::Deparse:                    0.56
    Math::Random:                  0.63
    Memoize:                       0
    String::Random:                0
    Test::Simple:                  0.44
    Time::HiRes:                   0
    Tree::DAG_Node:                1.04
    XML::LibXML:                   1.5
    XML::Parser::EasyTree:         0.01
    YAML:                          0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
