--- #YAML:1.0
name:               Algorithm-Evolutionary
version:            0.63
abstract:           Perl extension for performing paradigm-free evolutionary algorithms. 
author:
    - JJ Merelo <jj /at/ merelo.net>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    Algorithm::Permute:   0.01
    B::Deparse:           0.56
    Bit::Vector:          0
    Clone::Fast:          0
    constant:             0
    Math::Random:         0.63
    Memoize:              0
    Object::Array:        0
    String::Random:       0
    Test::More:           0
    Test::Pod:            0
    Test::Simple:         0.44
    Time::HiRes:          0
    Tree::DAG_Node:       1.04
    version:              0
    XML::LibXML:          1.5
    XML::Parser:          0
    XML::Parser::Style::EasyTree:  0.01
    YAML:                 0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
