--- #YAML:1.0
name:                Algorithm-Evolutionary
version:             0.59
abstract:            Perl extension for performing paradigm-free evolutionary algorithms. 
license:             ~
author:              
    - J. J. Merelo <jmerelo (at) geneura.ugr.es>
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    Algorithm::Permute:            0.01
    B::Deparse:                    0.56
    constant:                      0
    Math::Random:                  0.63
    Memoize:                       0
    String::Random:                0
    Test::Simple:                  0.44
    Time::HiRes:                   0
    Tree::DAG_Node:                1.04
    version:                       0
    XML::LibXML:                   1.5
    XML::Parser:                   0
    XML::Parser::EasyTree:         0.01
    YAML:                          0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
